spring:
  application:
    name: api-gateway


  cloud:

#    discovery:
#      enabled: true

    gateway:
      routes:
        - id: players
          uri: lb://players
          predicates:
            - Path=/players/**
          filters:
            - StripPrefix=1

        - id: teams
          uri: lb://teams
          predicates:
            - Path=/teams/**
          filters:
            - StripPrefix=1

        - id: fields
          uri: lb://fields
          predicates:
            - Path=/fields/**
          filters:
            - StripPrefix=1

        - id: tickets
          uri: lb://tickets
          predicates:
            - Path=/tickets/**
          filters:
            - StripPrefix=1

        - id: tournaments
          uri: lb://tournaments
          predicates:
            - Path=/tournaments/**
          filters:
            - StripPrefix=1

        - id: matches
          uri: lb://matches
          predicates:
            - Path=/matches/**
          filters:
            - StripPrefix=1


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  instance:
    prefer-ip-address: true